# Базовый образ с Python 3.11
FROM python:3.11-slim

# Установим рабочую директорию в контейнере
WORKDIR /app

# Копируем все файлы проекта в контейнер
COPY . /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем переменную окружения для работы с FastAPI
ENV PYTHONUNBUFFERED 1

# Открываем порт 8000 для FastAPI
EXPOSE 8000

# Запускаем сервер с помощью uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
